[package]
name = "qualtet-mock"
version = "2.14.0"
edition = "2021"
authors = ["yoshinorin"]
rust-version = "1.81"

[dependencies]
actix-web = "4.8.0"
log = "0.4.22"
env_logger = "0.11.5"
actix-cors = "0.7.0"

[profile.release]
strip = true
