[package]
name = "qualtet-mock"
version = "0.1.0"
edition = "2021"
authors = ["yoshinorin"]

[dependencies]
actix-web = "4.4.0"
log = "0.4.20"
env_logger = "0.10.1"
actix-cors = "0.6.5"

[profile.release]
strip = true
