[package]
name = "qualtet-mock"
version = "2.16.0"
edition = "2021"
authors = ["yoshinorin"]
rust-version = "1.84"

[dependencies]
actix-web = "4.9.0"
log = "0.4.25"
env_logger = "0.11.6"
actix-cors = "0.7.0"

[profile.release]
strip = true
