[package]
name = "qualtet-mock"
version = "2.16.0"
edition = "2024"
authors = ["yoshinorin"]
rust-version = "1.85.1"

[dependencies]
actix-web = "4.10.0"
log = "0.4.27"
env_logger = "0.11.7"
actix-cors = "0.7.1"

[profile.release]
strip = true
