[package]
name = "qualtet-mock"
version = "2.19.0"
edition = "2024"
authors = ["yoshinorin"]
rust-version = "1.90.0"

[dependencies]
actix-web = "4.11.0"
log = "0.4.27"
env_logger = "0.11.8"
actix-cors = "0.7.1"

[profile.release]
strip = true
