[package]
name = "qualtet-mock"
version = "2.13.0"
edition = "2021"
authors = ["yoshinorin"]
rust-version = "1.79"

[dependencies]
actix-web = "4.8.0"
log = "0.4.21"
env_logger = "0.10.1"
actix-cors = "0.6.5"

[profile.release]
strip = true
