name: CI

on:
  push:
    paths-ignore:
      - LICENSE
      - README.md

jobs:
  build:
    runs-on: ${{ matrix.target.os }}
    timeout-minutes: 360
    strategy:
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
          - { name: Windows, os: windows-latest, triple: x86_64-pc-windows-msvc }
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up rustup
        run: |
          rustup update
          rustup --version
          rustc --version
          cargo --version
      - name: cargo build
        # TODO: How to specify `rustc` version???
        run: cargo build
